const games = [
    {
        "juego": "7 Wonders Duel",
        "imagen": "https://cf.geekdo-images.com/zdagMskTF7wJBPjX74XsRw__square@2x/img/18sI3DQbHoswa4j69WJROdLmsCE=/150x150/filters:strip_icc()/pic2576399.jpg",
        "rank": "21",
        "complejidad": "2.227",
        "trata": "Un \"tira y afloja\" tenso solo para 2 personas. Construye una civilización y gana por guerra o ciencia. Muy estratégico.",
        "calificacion": "8.08186",
        "recomm_players": "2",
        "maxplayers": "2",
        "minplaytime": "30",
        "maxplaytime": "45",
        "minplayers": "2",
        "categoria": "Estrategia",
        "categoria2": "Draft",
        "categoria3": "Abstracto",
        "se_jugar": "Sí"
    },
    {
        "juego": "Brass: Birmingham",
        "imagen": "https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__square@2x/img/AP-frR3-R9xuL0dlW3nbE8ZH6ZM=/150x150/filters:strip_icc()/pic3490053.jpg",
        "rank": "1",
        "complejidad": "3.867",
        "trata": "Gestión económica pura y dura en la revolución industrial. Estrategia pesada, mucha planificación y partidas largas.",
        "calificacion": "8.57164",
        "recomm_players": "4",
        "maxplayers": "4",
        "minplaytime": "60",
        "maxplaytime": "180",
        "minplayers": "2",
        "categoria": "Estrategia",
        "categoria2": "Economía",
        "categoria3": "Construcción de Motores",
        "se_jugar": "Sí"
    },
    {
        "juego": "Clank!: Catacombs",
        "imagen": "https://cf.geekdo-images.com/cCLn9Mvb7jRSaZzHeUXhoQ__square@2x/img/4JcXRC29QiWIsKCuCbVHr7t4Rjo=/150x150/filters:strip_icc()/pic6937913.jpg",
        "rank": "61",
        "complejidad": "2.502",
        "trata": "Entra a una mazmorra, roba tesoros y sal corriendo antes de que el dragón te mate. Aventura y construcción de mazo.",
        "calificacion": "8.244",
        "recomm_players": "3",
        "maxplayers": "4",
        "minplaytime": "45",
        "maxplaytime": "90",
        "minplayers": "2",
        "categoria": "Construcción de Mazos",
        "categoria2": "Estrategia",
        "categoria3": "Abstracto",
        "se_jugar": "Sí"
    },
    {
        "juego": "Jaipur",
        "imagen": "https://cf.geekdo-images.com/_LTujSe_o16nvjDC-J0seA__square@2x/img/c4iIaPCaWuhBlxFF5Ir7HbA18fY=/150x150/filters:strip_icc()/pic5100947.jpg",
        "rank": "199",
        "complejidad": "1.465",
        "trata": "Mercado persa para 2 jugadores. Vende camellos y telas antes que tu rival. Rápido, táctico y adictivo.",
        "calificacion": "7.4816",
        "recomm_players": "2",
        "maxplayers": "2",
        "minplaytime": "30",
        "maxplaytime": "40",
        "minplayers": "2",
        "categoria": "Estrategia",
        "categoria2": "Colección de Sets",
        "categoria3": "Draft",
        "se_jugar": "Sí"
    },
    {
        "juego": "Just One",
        "imagen": "https://cf.geekdo-images.com/74haNunMBn85beBi-yIKwA__square@2x/img/DyXuOGohHV4ZpGsTSpZOGhUjiXk=/150x150/filters:strip_icc()/pic8669313.png",
        "rank": "155",
        "complejidad": "1.036",
        "trata": "Juego cooperativo de palabras. Todos escriben una pista para que uno adivine, ¡pero si repiten pista se borran! Cero estrés.",
        "calificacion": "7.59799",
        "recomm_players": "7",
        "maxplayers": "7",
        "minplaytime": "20",
        "maxplaytime": "50",
        "minplayers": "3",
        "categoria": "Familiar",
        "categoria2": "Abstracto",
        "categoria3": "Palabras",
        "se_jugar": "Sí"
    },
    {
        "juego": "Scout",
        "imagen": "https://cf.geekdo-images.com/cf0xxkevbwTGF3VUZymKjg__square@2x/img/a0hdSMiM1kX52ucbpc8IYEJ2uIM=/150x150/filters:strip_icc()/pic6398727.png",
        "rank": "102",
        "complejidad": "1.379",
        "trata": "Un juego de \"escalera\" donde no puedes reordenar las cartas de tu mano. Tienes que gestionar lo que te toca. Muy inteligente.",
        "calificacion": "7.80367",
        "recomm_players": "4",
        "maxplayers": "5",
        "minplaytime": "20",
        "maxplaytime": "45",
        "minplayers": "2",
        "categoria": "Juego de Cartas",
        "categoria2": "Tentando a la Suerte",
        "categoria3": "Colección de Sets",
        "se_jugar": "Sí"
    },
    {
        "juego": "Slay the Spire: The Board Game",
        "imagen": "https://cf.geekdo-images.com/PQzVclEoOQ_wr4e1V86kxA__square@2x/img/vQpWHmmY0oNQ90qoA7N_3w0vZ4Y=/150x150/filters:strip_icc()/pic8157856.png",
        "rank": "28",
        "complejidad": "2.913",
        "trata": "Juntos suben una torre. Eliges ruta, mejoras mazo y peleas contra jefes.",
        "calificacion": "8.67176",
        "recomm_players": "4",
        "maxplayers": "4",
        "minplaytime": "90",
        "maxplaytime": "180",
        "minplayers": "2",
        "categoria": "Construcción de Mazos",
        "categoria2": "Cooperativo",
        "categoria3": "Estrategia",
        "se_jugar": "Sí"
    },
    {
        "juego": "Terraforming Mars",
        "imagen": "https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZQ4rxw__square@2x/img/yRsHnxheXXQYHKsQYRcIdAMy_L8=/150x150/filters:strip_icc()/pic3536616.jpg",
        "rank": "8",
        "complejidad": "3.266",
        "trata": "Haz habitable Marte. Muchas cartas, recursos y combos. Largo y satisfactorio si te gusta gestionar.",
        "calificacion": "8.34238",
        "recomm_players": "4",
        "maxplayers": "5",
        "minplaytime": "120",
        "maxplaytime": "180",
        "minplayers": "2",
        "categoria": "Estrategia",
        "categoria2": "Construcción de Motores",
        "categoria3": "Economía",
        "se_jugar": "Sí"
    },
    {
        "juego": "The Crew: Planets",
        "imagen": "https://cf.geekdo-images.com/98LnQShydr11OBKS46xY-Q__square@2x/img/h4Jzqy5_oz3bVYF0qKgU_8M3rd8=/150x150/filters:strip_icc()/pic5687013.jpg",
        "rank": "88",
        "complejidad": "1.962",
        "trata": "La versión original espacial del anterior. Misiones lógicas cooperativas con cartas.",
        "calificacion": "7.76557",
        "recomm_players": "4",
        "maxplayers": "5",
        "minplaytime": "20",
        "maxplaytime": "120",
        "minplayers": "2",
        "categoria": "Cooperativo",
        "categoria2": "Estrategia",
        "categoria3": "Bazas",
        "se_jugar": "Sí"
    },
    {
        "juego": "The Quacks of Quedlinburg",
        "imagen": "https://cf.geekdo-images.com/pH5LgRL4mNRon-2NsSDb1Q__square@2x/img/aOdG7uW4wRSEwsHlm9BBivLPR7c=/150x150/filters:strip_icc()/pic6137509.png",
        "rank": "75",
        "complejidad": "1.942",
        "trata": "Saca ingredientes de tu bolsa para tu poción, pero si apuestas demasiado pueds explotar tu caldero. Gestión de riesgo y emoción.",
        "calificacion": "7.80574",
        "recomm_players": "4",
        "maxplayers": "4",
        "minplaytime": "50",
        "maxplaytime": "60",
        "minplayers": "2",
        "categoria": "Familiar",
        "categoria2": "GAMBLING",
        "categoria3": "Dados",
        "se_jugar": "Sí"
    },
    {
        "juego": "Wingspan",
        "imagen": "https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__square@2x/img/CK0WxvlVV7xaJf7phgNy3JklBXY=/150x150/filters:strip_icc()/pic4458123.jpg",
        "rank": "38",
        "complejidad": "2.475",
        "trata": "Atrae aves hermosas a tu reserva. Un juego relajante, precioso y de complejidad progresiva. Muy satisfactorio.",
        "calificacion": "8.00734",
        "recomm_players": "3",
        "maxplayers": "5",
        "minplaytime": "90",
        "maxplaytime": "120",
        "minplayers": "2",
        "categoria": "Estrategia",
        "categoria2": "Construcción de Motores",
        "categoria3": "Colección de Sets",
        "se_jugar": "Sí"
    },
    {
        "juego": "Harmonies",
        "imagen": "https://cf.geekdo-images.com/A_XP2_VN3ugyqPhezowB_w__square@2x/img/QXoK0xyr1ySNF8iHX1Gq3t8FDb4=/150x150/filters:strip_icc()/pic8026369.png",
        "rank": "54",
        "complejidad": "2.080",
        "trata": "Crea paisajes colocando fichas y atrae animales según los patrones que formes. Táctico, visualmente hermoso y muy dinámico.",
        "calificacion": "7.95000",
        "recomm_players": "3",
        "maxplayers": "4",
        "minplaytime": "30",
        "maxplaytime": "45",
        "minplayers": "1",
        "categoria": "Estrategia",
        "categoria2": "Colocación de Losetas",
        "categoria3": "Abstracto",
        "se_jugar": "Sí"
    },
    {
        "juego": "Dune: Imperium – Uprising",
        "imagen": "https://cf.geekdo-images.com/UVUkjMV_Q2paVUIUP30Vvw__square@2x/img/RtiFwvR-tHr93OXwocJCd2qULAU=/150x150/filters:strip_icc()/pic7664424.jpg",
        "rank": "5",
        "complejidad": "3.520",
        "trata": "Secuela independiente de Dune: Imperium que añade gusanos de arena, espías y conflicto directo. Tensión constante en Arrakis.",
        "calificacion": "8.701",
        "recomm_players": "4",
        "maxplayers": "6",
        "minplaytime": "60",
        "maxplaytime": "160",
        "minplayers": "1",
        "categoria": "Estrategia",
        "categoria2": "Construcción de Mazos",
        "categoria3": "Gestión de Mano",
        "se_jugar": "No"
    },
    {
        "juego": "BANG! The Dice Game",
        "imagen": "https://cf.geekdo-images.com/BLTFau1Ue-gjX6geQdYrjQ__square@2x/img/77vEf9C1aBdjXS_XrohtgVdp_9A=/150x150/filters:strip_icc()/pic2909713.jpg",
        "rank": "851",
        "complejidad": "1.280",
        "trata": "Vaqueros en el viejo oeste. Nadie sabe qué eres (Sheriff, Forajido, Renegado) y tiras dados para disparar. Caótico y rápido.",
        "calificacion": "6.88135",
        "recomm_players": "3",
        "maxplayers": "8",
        "minplaytime": "25",
        "maxplaytime": "50",
        "minplayers": "3",
        "categoria": "Deducción Social",
        "categoria2": "Juego de Cartas",
        "categoria3": "Take That (Ataque)",
        "se_jugar": "Sí"
    },
    {
        "juego": "Binding of Isaac: Four Souls",
        "imagen": "https://cf.geekdo-images.com/_W2HUy9gZr0Xr603kGccTw__square@2x/img/qTeKkSGqykduJ7q7wvfsWUbxIck=/150x150/filters:strip_icc()/pic7407873.jpg",
        "rank": "2757",
        "complejidad": "2.750",
        "trata": "Promesas, sobornos, traiciones, muerte, caos. Los monstruos de estas cartas son por los que menos te debes preocupar.",
        "calificacion": "8.32877",
        "recomm_players": "3",
        "maxplayers": "4",
        "minplaytime": "80",
        "maxplaytime": "180",
        "minplayers": "2",
        "categoria": "Take That (Ataque)",
        "categoria2": "Dados",
        "categoria3": "Construcción de Motores",
        "se_jugar": "Sí"
    },
    {
        "juego": "Camel Up (Second Edition)",
        "imagen": "https://cf.geekdo-images.com/qnR2V3YsW963_JaVznBjsw__square@2x/img/bXIX5x9DmjIl305GoPblsI4CBJ4=/150x150/filters:strip_icc()/pic8584959.jpg",
        "rank": "263",
        "complejidad": "1.507",
        "trata": "Una carrera de camellos loquísima donde apuestas al ganador. Puro azar, gritos y risas. Cero estrategia seria.",
        "calificacion": "7.5509",
        "recomm_players": "5",
        "maxplayers": "8",
        "minplaytime": "30",
        "maxplaytime": "35",
        "minplayers": "3",
        "categoria": "GAMBLING",
        "categoria2": "Dados",
        "categoria3": "Tentando a la Suerte",
        "se_jugar": "Sí"
    },
    {
        "juego": "Carcassonne Plus 2017",
        "imagen": "https://cf.geekdo-images.com/TrWotolWZDtv2_wv3V1ooQ__square@2x/img/lRxQFVwCUKO4cfWqROSxVpyyaOQ=/150x150/filters:strip_icc()/pic3746547.jpg",
        "rank": "236",
        "complejidad": "1.956",
        "trata": "Construye un mapa medieval pieza a pieza. Muy visual, relajado y clásico. Reglas simples y rápidas.",
        "calificacion": "8.06413",
        "recomm_players": "4",
        "maxplayers": "6",
        "minplaytime": "30",
        "maxplaytime": "50",
        "minplayers": "2",
        "categoria": "Colocación de Losetas",
        "categoria2": "Abstracto",
        "categoria3": "Estrategia",
        "se_jugar": "Sí"
    },
    {
        "juego": "Century: Golem Edition",
        "imagen": "https://cf.geekdo-images.com/1bihoShOuqaCuZJXB3Q2gQ__square@2x/img/HRLLJMQdYY08VFU8nSJ1ot0dLfc=/150x150/filters:strip_icc()/pic3936124.jpg",
        "rank": "273",
        "complejidad": "1.716",
        "trata": "Eres un comerciante de Gemas. Mecánica sencilla de intercambiar gemas para comprar cartas. Bonito, fluido y fácil de entender.",
        "calificacion": "7.58032",
        "recomm_players": "4",
        "maxplayers": "5",
        "minplaytime": "30",
        "maxplaytime": "45",
        "minplayers": "2",
        "categoria": "Estrategia",
        "categoria2": "Construcción de Motores",
        "categoria3": "Gestión de Mano",
        "se_jugar": "Sí"
    },
    {
        "juego": "Coup",
        "imagen": "https://cf.geekdo-images.com/MWhSY_GOe2-bmlQ2rntSVg__square@2x/img/iorohp6ykX6R0z3cHZFws1nN4QE=/150x150/filters:strip_icc()/pic2016054.jpg",
        "rank": "701",
        "complejidad": "1.411",
        "trata": "Mentiras cara a cara. Partidas de 10 minutos donde gana el que mejor miente sobre las cartas que tiene. Tensión social pura.",
        "calificacion": "6.97622",
        "recomm_players": "6",
        "maxplayers": "6",
        "minplaytime": "15",
        "maxplaytime": "20",
        "minplayers": "2",
        "categoria": "Deducción Social",
        "categoria2": "Fiesta",
        "categoria3": "Faroleo",
        "se_jugar": "Sí"
    },
    {
        "juego": "Don't Get Got!",
        "imagen": "https://cf.geekdo-images.com/03kajQYeuaJQP8VydWnOng__square@2x/img/y9t8XWJ14xkooUh_fSWVjO4wEuA=/150x150/filters:strip_icc()/pic4346773.jpg",
        "rank": "2379",
        "complejidad": "1.079",
        "trata": "Misiones secretas que debes cumplir MIENTRAS juegas a otra cosa o cenas. Paranoia constante toda la noche.",
        "calificacion": "6.95834",
        "recomm_players": "8",
        "maxplayers": "10",
        "minplaytime": "N/A",
        "maxplaytime": "N/A",
        "minplayers": "2",
        "categoria": "Fiesta",
        "categoria2": "Deducción Social",
        "categoria3": "Estrategia",
        "se_jugar": "Sí"
    },
    {
        "juego": "Exploding Kittens",
        "imagen": "https://cf.geekdo-images.com/9nigz-uMeFNk0xs8EhWFMQ__square@2x/img/UaER5Nkiruonri1quoBsPG5S5aE=/150x150/filters:strip_icc()/pic4372702.jpg",
        "rank": "2220",
        "complejidad": "1.067",
        "trata": "Ruleta rusa con gatos. Roba cartas y reza para que no te salga la bomba. Sencillo y ligero mentalmente.",
        "calificacion": "7.06293",
        "recomm_players": "5",
        "maxplayers": "10",
        "minplaytime": "10",
        "maxplaytime": "15",
        "minplayers": "2",
        "categoria": "Fiesta",
        "categoria2": "Juego de Cartas",
        "categoria3": "Take That (Ataque)",
        "se_jugar": "Sí"
    },
    {
        "juego": "Fake Artist Goes to New York",
        "imagen": "https://cf.geekdo-images.com/5Q5YHxJeVp6PAhfv5Ct0-g__square@2x/img/yoaQGfed_IEy4qLsAbtjqlZEJhE=/150x150/filters:strip_icc()/pic3678404.png",
        "rank": "738",
        "complejidad": "1.097",
        "trata": "Todos dibujan algo juntos menos uno (el impostor) que no sabe qué es. Hay que descubrir quién dibuja sin saber. Creativo y social.",
        "calificacion": "7.11565",
        "recomm_players": "6",
        "maxplayers": "10",
        "minplaytime": "20",
        "maxplaytime": "25",
        "minplayers": "5",
        "categoria": "Cooperativo",
        "categoria2": "Deducción Social",
        "categoria3": "Faroleo",
        "se_jugar": "Sí"
    },
    {
        "juego": "Hanabi",
        "imagen": "https://cf.geekdo-images.com/JDVksMwfcqoem1k_xtZrOA__square@2x/img/qJyqQ2QOfNAuTBkvOZRAcbnQkLk=/150x150/filters:strip_icc()/pic2007286.jpg",
        "rank": "583",
        "complejidad": "1.692",
        "trata": "Cooperativo donde todos ven tus cartas menos tú. Hay que dar pistas limitadas para ordenar las cartas de manera correcta. Comunicación tensa.",
        "calificacion": "7.03098",
        "recomm_players": "4",
        "maxplayers": "5",
        "minplaytime": "40",
        "maxplaytime": "90",
        "minplayers": "2",
        "categoria": "Juego de Cartas",
        "categoria2": "Estrategia",
        "categoria3": "Juego de Cartas",
        "se_jugar": "Sí"
    },
    {
        "juego": "Here to Slay",
        "imagen": "https://cf.geekdo-images.com/ozUv3be9fcf28tJk30bNow__square@2x/img/l9db62jJv4NUTPxo3TxBwXXnM4g=/150x150/filters:strip_icc()/pic5181432.jpg",
        "rank": "1493",
        "complejidad": "1.685",
        "trata": "Forma un equipo de héroes y mata monstruos. Estrategia ligera con mucha interacción para destruir los planes de otros.",
        "calificacion": "6.88243",
        "recomm_players": "4",
        "maxplayers": "6",
        "minplaytime": "20",
        "maxplaytime": "50",
        "minplayers": "2",
        "categoria": "Construcción de Motores",
        "categoria2": "Take That (Ataque)",
        "categoria3": "Estrategia",
        "se_jugar": "Sí"
    },
    {
        "juego": "Illusion",
        "imagen": "https://cf.geekdo-images.com/jcFaI9hr6iXwpwCZT-ifHA__square@2x/img/wQU1G7b8umlPoAz6_vuUQuUvQ4M=/150x150/filters:strip_icc()/pic3979771.png",
        "rank": "1689",
        "complejidad": "1.045",
        "trata": "¿Confías en tus ojos? Tienes que ordenar cartas según qué color ocupa más espacio visualmente. Sencillo y para cualquiera.",
        "calificacion": "6.70812",
        "recomm_players": "5",
        "maxplayers": "5",
        "minplaytime": "15",
        "maxplaytime": "20",
        "minplayers": "2",
        "categoria": "Fiesta",
        "categoria2": "Familiar",
        "categoria3": "Abstracto",
        "se_jugar": "Sí"
    },
    {
        "juego": "Love Letter Classic",
        "imagen": "https://cf.geekdo-images.com/-ZtsuRUlLrCcxMDsWC445A__square@2x/img/wAKBqTuzgBde8KiAWJkQ7c0ZfBY=/150x150/filters:strip_icc()/pic8828682.jpg",
        "rank": "329",
        "complejidad": "1.114",
        "trata": "Juego de solo 16 cartas. Deducción minimalista y rondas de 3 minutos. Intentas ser el último jugador en partida.",
        "calificacion": "7.50524",
        "recomm_players": "4",
        "maxplayers": "6",
        "minplaytime": "20",
        "maxplaytime": "30",
        "minplayers": "2",
        "categoria": "Abstracto",
        "categoria2": "Estrategia",
        "categoria3": "Faroleo",
        "se_jugar": "Sí"
    },
    {
        "juego": "Poker",
        "imagen": "https://cf.geekdo-images.com/QhsvR9GY0LbTpj27fairWA__square@2x/img/-Qrgb5xdUwx1JTsKJfgFyJqCjTE=/150x150/filters:strip_icc()/pic186610.jpg",
        "rank": "1401",
        "complejidad": "2.434",
        "trata": "El clásico de apuestas, faroleo y psicología.",
        "calificacion": "6.7071",
        "recomm_players": "4",
        "maxplayers": "10",
        "minplaytime": "5",
        "maxplaytime": "15",
        "minplayers": "2",
        "categoria": "Juego de Cartas",
        "categoria2": "Estrategia",
        "categoria3": "Colección de Sets",
        "se_jugar": "Sí"
    },
    {
        "juego": "Santorini",
        "imagen": "https://cf.geekdo-images.com/665Ply7Ho1WVf1v1iZlWeg__square@2x/img/1942wlcJzFw8KMKXh4Af_rnknWE=/150x150/filters:strip_icc()/pic3283110.png",
        "rank": "299",
        "complejidad": "1.723",
        "trata": "Como un ajedrez 3D simplificado con poderes de dioses griegos. Muy visualmente bonito y de pensar el siguiente paso.",
        "calificacion": "7.34047",
        "recomm_players": "2",
        "maxplayers": "4",
        "minplaytime": "10",
        "maxplaytime": "20",
        "minplayers": "2",
        "categoria": "Estrategia",
        "categoria2": "Abstracto",
        "categoria3": "Familiar",
        "se_jugar": "Sí"
    },
    {
        "juego": "Sea Salt & Paper",
        "imagen": "https://cf.geekdo-images.com/CIh_rXKoRw9z8K0PJxT8nQ__square@2x/img/1SqcyWH4W4qgZxYow0j4fCXO4GQ=/150x150/filters:strip_icc()/pic6973911.jpg",
        "rank": "272",
        "complejidad": "1.479",
        "trata": "Origami y colección de cartas. Rápido, muy bonito y con un toque de riesgo: ¿cierras la ronda ya o te arriesgas por más puntos?",
        "calificacion": "7.50621",
        "recomm_players": "2",
        "maxplayers": "4",
        "minplaytime": "30",
        "maxplaytime": "150",
        "minplayers": "2",
        "categoria": "Juego de Cartas",
        "categoria2": "Colección de Sets",
        "categoria3": "Draft",
        "se_jugar": "Sí"
    },
    {
        "juego": "Sushi Go Party!",
        "imagen": "https://cf.geekdo-images.com/jvYmb5EFnoXyiCB68gbybg__square@2x/img/tKKJl_ycc0bKFNxyPZs-bmO_IRE=/150x150/filters:strip_icc()/pic3031286.jpg",
        "rank": "279",
        "complejidad": "1.316",
        "trata": "Pasa las cartas y arma el mejor menú de sushi. Draft sencillo, adorable y con muchas opciones de menú diferentes.",
        "calificacion": "7.37737",
        "recomm_players": "4",
        "maxplayers": "8",
        "minplaytime": "40",
        "maxplaytime": "60",
        "minplayers": "2",
        "categoria": "Construcción de Motores",
        "categoria2": "Estrategia",
        "categoria3": "Economía",
        "se_jugar": "Sí"
    },
    {
        "juego": "Terraforming Mars: Colonies",
        "imagen": "https://cf.geekdo-images.com/OyCyHETRL-RzzYKlF8jshA__square@2x/img/y4-EtNgrA0cpxon3D_QZF3iPwFY=/150x150/filters:strip_icc()/pic4193099.jpg",
        "rank": "N/A",
        "complejidad": "2.990",
        "trata": "Expansión: Añade comercio con lunas lejanas para obtener recursos extra. Requiere el juego base.",
        "calificacion": "8.10271",
        "recomm_players": "4",
        "maxplayers": "5",
        "minplaytime": "120",
        "maxplaytime": "180",
        "minplayers": "2",
        "categoria": "Estrategia",
        "categoria2": "Construcción de Motores",
        "categoria3": "Economía",
        "se_jugar": "Sí"
    },
    {
        "juego": "Terraforming Mars: Prelude",
        "imagen": "https://cf.geekdo-images.com/2qrpbgsKEcvu5RLXpb6fgw__square@2x/img/V0ecQPPz4feezduNsWXj2npNyAQ=/150x150/filters:strip_icc()/pic4137234.jpg",
        "rank": "N/A",
        "complejidad": "2.544",
        "trata": "Expansión: Acelera el inicio del juego dándote un empujón de recursos iniciales. Imprescindible para partidas más rápidas.",
        "calificacion": "8.84557",
        "recomm_players": "4",
        "maxplayers": "5",
        "minplaytime": "120",
        "maxplaytime": "180",
        "minplayers": "2",
        "categoria": "Estrategia",
        "categoria2": "Construcción de Motores",
        "categoria3": "Economía",
        "se_jugar": "Sí"
    },
    {
        "juego": "Terraforming Mars: Venus Next",
        "imagen": "https://cf.geekdo-images.com/XuQN5HlG2bLbQu3AlQQgbQ__square@2x/img/SnjC4DmXTm26AJbgPGdjSCJI1hc=/150x150/filters:strip_icc()/pic3767139.jpg",
        "rank": "N/A",
        "complejidad": "2.855",
        "trata": "Expansión: Añade un tablero de Venus y más cartas. Más opciones, pero alarga la partida.",
        "calificacion": "7.56899",
        "recomm_players": "4",
        "maxplayers": "5",
        "minplaytime": "120",
        "maxplaytime": "180",
        "minplayers": "2",
        "categoria": "Estrategia",
        "categoria2": "Construcción de Motores",
        "categoria3": "Economía",
        "se_jugar": "Sí"
    },
    {
        "juego": "That's Not a Hat",
        "imagen": "https://cf.geekdo-images.com/y_8E6IhpFg5z-_9KHdQYYQ__square@2x/img/STvKWgkzSpPOLJDcPvGgIVb0hF8=/150x150/filters:strip_icc()/pic7386321.jpg",
        "rank": "1153",
        "complejidad": "1.059",
        "trata": "Juego de memoria donde te regalas objetos absurdos y mientes si no recuerdas qué era. No sabrás si dudas más de ellos o de ti.",
        "calificacion": "7.01697",
        "recomm_players": "6",
        "maxplayers": "8",
        "minplaytime": "10",
        "maxplaytime": "20",
        "minplayers": "3",
        "categoria": "Faroleo",
        "categoria2": "Memoria",
        "categoria3": "Juego de Cartas",
        "se_jugar": "Sí"
    },
    {
        "juego": "The Mind",
        "imagen": "https://cf.geekdo-images.com/q_JGK291hrhnhiRB0667oA__square@2x/img/kwvmi_9kE-YSurdoClplaRx2Aac=/150x150/filters:strip_icc()/pic3979766.png",
        "rank": "1062",
        "complejidad": "1.075",
        "trata": "El grupo debe jugar cartas del 1 al 100 en orden ascendente SIN HABLAR ni hacerse señas. Conexión mental o desastre total.",
        "calificacion": "6.72795",
        "recomm_players": "3",
        "maxplayers": "4",
        "minplaytime": "20",
        "maxplaytime": "60",
        "minplayers": "2",
        "categoria": "Fiesta",
        "categoria2": "Draft",
        "categoria3": "",
        "se_jugar": "Sí"
    },
    {
        "juego": "Ultimate Werewolf",
        "imagen": "https://cf.geekdo-images.com/dncdxD1g4dxMh9e8oKlzbg__square@2x/img/sjunSmSxlO8okxMja7nwfTwQRrU=/150x150/filters:strip_icc()/pic1878492.png",
        "rank": "N/A",
        "complejidad": "1.511",
        "trata": "Un pueblo duerme, los lobos matan. El clásico juego de roles ocultos y debate para grupos grandes.",
        "calificacion": "6.99734",
        "recomm_players": "7",
        "maxplayers": "8",
        "minplaytime": "15",
        "maxplaytime": "60",
        "minplayers": "5",
        "categoria": "Fiesta",
        "categoria2": "Deducción Social",
        "categoria3": "Faroleo",
        "se_jugar": "Sí"
    },
    {
        "juego": "Ultimate Werewolf: Artifacts",
        "imagen": "https://cf.geekdo-images.com/zQZ7oaiVND67tN29Cyj2eg__square@2x/img/SQ4njcNZAdeNYU_9pYmZsPLjSZ8=/150x150/filters:strip_icc()/pic2060080.png",
        "rank": "N/A",
        "complejidad": "1.400",
        "trata": "Variante: Añade objetos mágicos al juego base de Hombres Lobo para darle más caos a la deducción.",
        "calificacion": "6.7968",
        "recomm_players": "7",
        "maxplayers": "10+",
        "minplaytime": "15",
        "maxplaytime": "60",
        "minplayers": "5",
        "categoria": "Fiesta",
        "categoria2": "Deducción Social",
        "categoria3": "Faroleo",
        "se_jugar": "Sí"
    },
    {
        "juego": "Virus!",
        "imagen": "https://cf.geekdo-images.com/7Xx4ipXV4lf0Q9mWwitf2w__square@2x/img/HYWMpkoP5c17AR_7ZnAYd4-TNGc=/150x150/filters:strip_icc()/pic6008974.jpg",
        "rank": "1845",
        "complejidad": "1.057",
        "trata": "Infecta los órganos de tus rivales y cura los tuyos. Muy ligero, rápido y de \"molestar\" al vecino. Éxito seguro.",
        "calificacion": "6.71479",
        "recomm_players": "4",
        "maxplayers": "6",
        "minplaytime": "10",
        "maxplaytime": "60",
        "minplayers": "2",
        "categoria": "Gestión de Mano",
        "categoria2": "Draft",
        "categoria3": "Take That (Ataque)",
        "se_jugar": "Sí"
    }
    ,
    {
        "juego": "Space Base",
        "imagen": "https://cf.geekdo-images.com/MHhQxXVjiaa6C-04nGiIWw__square@2x/img/Igac3TwjsIF5dNV_iVUpaoBKISM=/150x150/filters:strip_icc()/pic6640638.jpg",
        "rank": "220",
        "complejidad": "2.129",
        "trata": "Tira dados y obtén recompensas ¡incluso en el turno de los demás! Construye tu flota espacial y genera recursos sin parar.",
        "calificacion": "7.53922",
        "recomm_players": "4",
        "maxplayers": "5",
        "minplaytime": "60",
        "maxplaytime": "90",
        "minplayers": "2",
        "categoria": "Dados",
        "categoria2": "Construcción de Motores",
        "categoria3": "",
        "se_jugar": "No"
    },
    {
        "juego": "The Crew: Mission Deep Sea",
        "imagen": "https://cf.geekdo-images.com/VuBqZ1sMaDAVVHF_OEJP4g__square@2x/img/rLREPDJegnVrQC_3_5Y-N53TJSk=/150x150/filters:strip_icc()/pic5988903.jpg",
        "rank": "44",
        "complejidad": "2.049",
        "trata": "Rondas cooperativas pero con misiones específicas que cumplir en silencio. Complejidad media y adictivo.",
        "calificacion": "8.06432",
        "recomm_players": "4",
        "maxplayers": "5",
        "minplaytime": "20",
        "maxplaytime": "120",
        "minplayers": "2",
        "categoria": "Cooperativo",
        "categoria2": "Estrategia",
        "categoria3": "Bazas",
        "se_jugar": "No"
    },
    {
        "juego": "The Red Cathedral",
        "imagen": "https://cf.geekdo-images.com/-PuiCnbxlBzMSjnUegp9AQ__square@2x/img/skw8UW5ngkEzti-N9a7KyX8jrHU=/150x150/filters:strip_icc()/pic5556025.jpg",
        "rank": "216",
        "complejidad": "2.815",
        "trata": "Construye la catedral de San Basilio usando dados y recursos. Estrategia media, muy eurogame pero accesible.",
        "calificacion": "7.66871",
        "recomm_players": "3",
        "maxplayers": "4",
        "minplaytime": "80",
        "maxplaytime": "100",
        "minplayers": "2",
        "categoria": "Estrategia",
        "categoria2": "Economía",
        "categoria3": "Dados",
        "se_jugar": "No"
    },
    {
        "juego": "Throw Throw Burrito",
        "imagen": "https://cf.geekdo-images.com/5ClVKrQcLkzRdBGiEfjevQ__square@2x/img/eWImQdV-SnDJyzG_o8kYPhfqoZg=/150x150/filters:strip_icc()/pic7073068.jpg",
        "rank": "3692",
        "complejidad": "1.104",
        "trata": "Juego de cartas mezclado con balón prisionero. Si juntas cartas iguales, le tiras un burrito de espuma a tu amigo. Caos físico.",
        "calificacion": "6.2414",
        "recomm_players": "6",
        "maxplayers": "6",
        "minplaytime": "10",
        "maxplaytime": "15",
        "minplayers": "2",
        "categoria": "Fiesta",
        "categoria2": "Destreza",
        "categoria3": "Colección de Sets",
        "se_jugar": "No"
    },
    {
        "juego": "Virus! 2 Evolution",
        "imagen": "https://cf.geekdo-images.com/4EiAemAumbUpbnfZpd_YWw__square@2x/img/qZOktnx9I5YdVy53aFCLTUwWEBg=/150x150/filters:strip_icc()/pic7281385.jpg",
        "rank": "N/A",
        "complejidad": "1.346",
        "trata": "Expansión: Añade virus evolucionados y nuevas medicinas. Más caos para el juego base.",
        "calificacion": "6.97906",
        "recomm_players": "4",
        "maxplayers": "6",
        "minplaytime": "10",
        "maxplaytime": "60",
        "minplayers": "2",
        "categoria": "Gestión de Mano",
        "categoria2": "Draft",
        "categoria3": "Take That (Ataque)",
        "se_jugar": "No"
    }

];
